server:
  port: 8010

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://39.108.190.161:3306/bore?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true
    username: root
    password: Shyanzhi123@
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 15

  jpa:
    show-sql: true

module:
  domain:
    static: http://bgbr-static.oss-cn-shenzhen.aliyuncs.com
    main: http://localhost:8080
    cookie: localhost

# Zookeeper
dubbo:
  protocol:
    port: 30001
  application:
    name: spring-boot-provider
  registry:
    address: zookeeper://47.52.132.127:2181